# Global settings applied to the whole site. See more info here: https://www.netlify.com/docs/netlify-toml-reference/

[build]
  publish = "build_production"
  command = "yarn run production"

[build.environment]
  PHP_VERSION = "8.2"